version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android
        
    steps:
      - checkout
      - run: cd client; chmod +x ./gradlew; ./gradlew assembleRelease
      - store_artifacts:
          path: ./client/app/build/outputs/apk
          destination: apk